import type { Metadata } from 'next';

import '@/styles/globals.css';
import Header from '@/components/Header';

export const metadata: Metadata = {
	title: 'Weather Llama',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={'min-h-screen'}>
				<Header />
				{children}
			</body>
		</html>
	);
}
