import '@/styles/globals.css';

import { createContext, useContext, useState } from 'react';
import Header from '@/components/Header';
import { AnimatePresence, motion } from 'framer-motion';

import type { Metadata } from 'next';
import BackdropProvider from '@/components/BackdropProvider';
export const metadata: Metadata = {
	title: 'Weather Llama',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={''}>
				<BackdropProvider>
					<Header />
					{children}
				</BackdropProvider>
			</body>
		</html>
	);
}
